import { Page } from "puppeteer-core";
import { BaseCarrier } from "../base-carrier";
import { DocumentResult } from "../types";

// ─── Selectors ────────────────────────────────────────────────────────────────
// Lemonade uses stable data-atn-id attributes rather than IDs or class names,
// which makes these selectors resilient to style/layout changes.

const SELECTORS = {
  // Login — email-only (passwordless)
  emailInput:    'input[data-atn-id="email-input"]',
  submitButton:  'button[data-atn-id="submit-button"]',

  // OTP screen — 6 discrete single-character inputs
  otpInputs:     'input[autocomplete="one-time-code"]',

  // Post-auth dashboard — policy card title element.
  // The full class string contains an autogenerated hash (e.g. "sc-bdfBwQ kpQYKR"),
  // but the styled-component display name segment is stable across builds.
  policyCard:    'div[class*="HomeExistingProductItem__Title"]',
} as const;

/** Lemonade auto-triggers the OTP immediately after email submit */
const OTP_INPUT_COUNT = 6;

const LEMONADE_LOGIN_URL  = "https://www.lemonade.com/login#email";
const LEMONADE_POLICY_URL_PATTERN = /^https:\/\/me\.lemonade\.com\/policy\//;

const DOM_TIMEOUT  = 20_000;
const NAV_TIMEOUT  = 30_000;

// ─── LemonadeCarrier ──────────────────────────────────────────────────────────

/**
 * LemonadeCarrier
 * ---------------
 * Concrete extractor for Lemonade's member portal (renters / homeowners).
 *
 * Auth flow (passwordless OTP):
 *   1. Navigate to /login#email
 *   2. Fill email using data-atn-id attributes  →  click Submit
 *   3. Lemonade immediately sends the OTP — no explicit trigger needed
 *   4. Wait for 6 individual OTP inputs to appear
 *   5. Type each digit of the code into its own input field
 *
 * Document flow:
 *   1. Land on the dashboard after OTP
 *   2. Click the first policy card title (class*="HomeExistingProductItem__Title")
 *   3. Intercept the new tab opened by the click via browser().waitForTarget()
 *   4. Wait for the policy page to settle, then capture it as a PDF via page.pdf()
 */
export class LemonadeCarrier extends BaseCarrier {
  readonly carrierId = "lemonade";

  // ─── Page Configuration ───────────────────────────────────────────────────

  protected override async configurePage(page: Page): Promise<void> {
    page.setDefaultTimeout(DOM_TIMEOUT);
    page.setDefaultNavigationTimeout(NAV_TIMEOUT);
  }

  // ─── login() — required by BaseCarrier ───────────────────────────────────

  /**
   * Lemonade is passwordless: login only requires an email address.
   * Orchestrates `navigateToLogin` → `submitCredentials`.
   */
  protected async login(
    page: Page,
    credentials: Record<string, string>
  ): Promise<void> {
    const email = LemonadeCarrier.extractEmail(credentials);

    await this.navigateToLogin(page);
    await this.submitCredentials(page, email);
  }

  // ─── Step 1: Navigate ─────────────────────────────────────────────────────

  private async navigateToLogin(page: Page): Promise<void> {
    await page.goto(LEMONADE_LOGIN_URL, { waitUntil: "networkidle2" });

    // Confirm the email input is rendered before proceeding
    await page.waitForSelector(SELECTORS.emailInput, {
      visible: true,
      timeout: DOM_TIMEOUT,
    });
  }

  // ─── Step 2: Submit Email ─────────────────────────────────────────────────

  /**
   * Fills the email field and clicks Submit.
   * No password field — Lemonade's portal transitions directly to the OTP screen.
   */
  private async submitCredentials(page: Page, email: string): Promise<void> {
    // Clear any autofilled value
    await page.evaluate(
      (sel) => ((document.querySelector(sel) as HTMLInputElement).value = ""),
      SELECTORS.emailInput
    );
    await page.type(SELECTORS.emailInput, email, { delay: 40 });

    await page.waitForSelector(SELECTORS.submitButton, { visible: true });
    await page.click(SELECTORS.submitButton);

    // Lemonade transitions the SPA to the OTP screen without a full navigation.
    // Gate on the first OTP input appearing rather than waitForNavigation.
    await page.waitForSelector(SELECTORS.otpInputs, {
      visible: true,
      timeout: DOM_TIMEOUT,
    });
  }

  // ─── triggerMfa() — required by BaseCarrier ──────────────────────────────

  /**
   * Lemonade triggers the OTP automatically when the email is submitted.
   * The only work here is confirming the OTP inputs are visible before the
   * base class transitions the state machine to AWAITING_MFA.
   */
  protected async triggerMfa(page: Page): Promise<void> {
    // The OTP inputs should already be visible from submitCredentials,
    // but we wait again defensively in case of slow network renders.
    await page.waitForSelector(SELECTORS.otpInputs, {
      visible: true,
      timeout: DOM_TIMEOUT,
    });
  }

  // ─── submitMfaInBrowser() — required by BaseCarrier ──────────────────────

  /**
   * Distributes the 6-digit OTP code across Lemonade's individual digit inputs.
   *
   * Each input accepts exactly one character. Typing the full code into the
   * first field does not work — the portal listens to individual `input` events
   * per cell and does not relay characters to subsequent inputs automatically.
   */
  protected async submitMfaInBrowser(page: Page, code: string): Promise<void> {
    // Upstash Redis auto-deserializes values that look like numbers into actual
    // Number types. An all-digit OTP like "123456" comes back as 123456, which
    // has no .replace() method. String() normalises either type safely.
    const digits = String(code).replace(/\s/g, "").split("");

    if (digits.length !== OTP_INPUT_COUNT) {
      throw new Error(
        `LemonadeCarrier: OTP must be ${OTP_INPUT_COUNT} digits, got ${digits.length}`
      );
    }

    // Re-query inputs at submission time to get a fresh NodeList after any
    // React re-renders that may have replaced DOM nodes since triggerMfa.
    const inputs = await page.$$(SELECTORS.otpInputs);

    if (inputs.length < OTP_INPUT_COUNT) {
      throw new Error(
        `LemonadeCarrier: Expected ${OTP_INPUT_COUNT} OTP inputs, found ${inputs.length}`
      );
    }

    for (let i = 0; i < OTP_INPUT_COUNT; i++) {
      await inputs[i].click();
      // Use type() on the element handle for focus + keystroke fidelity
      await inputs[i].type(digits[i], { delay: 60 });
    }

    // After the last digit, Lemonade auto-submits — wait for the dashboard.
    await page.waitForNavigation({ waitUntil: "networkidle2", timeout: NAV_TIMEOUT });
  }

  // ─── fetchDocuments() — required by BaseCarrier ──────────────────────────

  /**
   * Navigates to the first policy card on the dashboard and captures the
   * declarations page as a PDF buffer using page.pdf().
   *
   * The policy page at https://me.lemonade.com/policy/[POLICY_ID] acts as
   * the declarations page — we treat the full-page PDF as the document.
   */
  protected async fetchDocuments(page: Page): Promise<DocumentResult["documents"]> {
    // ── 1. Wait for the dashboard policy card ────────────────────────────────

    await page.waitForSelector(SELECTORS.policyCard, {
      visible: true,
      timeout: DOM_TIMEOUT,
    });

    // ── 2. Intercept the new tab opened by the policy card click ────────────
    //
    // Clicking the policy card fires a JS event that calls window.open(),
    // opening the policy page in a new browser tab rather than navigating the
    // current page. Neither waitForNavigation nor waitForFunction on
    // window.location.href will ever resolve on the original page.
    //
    // The correct approach is to race a waitForTarget listener against the
    // click, then promote the new Target to a Page and drive it from there.

    const newTabTarget = await Promise.all([
      // Resolves with the first new Target whose URL contains "/policy/"
      page.browser().waitForTarget(
        (t) => t.url().includes("/policy/"),
        { timeout: NAV_TIMEOUT }
      ),
      // Trigger the click after the listener is registered so no events are missed
      page.click(SELECTORS.policyCard),
    ]).then(([target]) => target);

    // Promote the Target to a fully usable Page instance
    const policyPage = await newTabTarget.page();

    if (!policyPage) {
      throw new Error("LemonadeCarrier: Failed to obtain Page from new-tab target");
    }

    // Wait for the policy page's network activity to settle before printing
    await policyPage.waitForNavigation({
      waitUntil: "networkidle2",
      timeout:   NAV_TIMEOUT,
    }).catch(() => {
      // Non-fatal: the page may have already finished loading before we await
    });

    const policyUrl = policyPage.url();

    if (!LEMONADE_POLICY_URL_PATTERN.test(policyUrl)) {
      throw new Error(
        `LemonadeCarrier: Unexpected URL in new tab: ${policyUrl}`
      );
    }

    // Extract the policy ID from the URL for a meaningful filename
    const policyId = policyUrl.split("/policy/")[1]?.split("?")[0] ?? "unknown";

    // ── 3. Let the SPA finish rendering before printing ──────────────────────

    await policyPage.waitForFunction(
      () => !document.querySelector('[data-loading="true"]'),
      { timeout: DOM_TIMEOUT }
    ).catch(() => {
      // Non-fatal: proceed even if the loading guard selector is absent
    });

    // ── 4. Capture the new tab as a PDF ──────────────────────────────────────

    // page.pdf() returns Uint8Array in puppeteer-core; wrap in Buffer for
    // consistency with the ExtractedDocument interface.
    const pdfBytes = await policyPage.pdf({
      format:              "Letter",
      printBackground:     true,
      margin:              { top: "0.5in", right: "0.5in", bottom: "0.5in", left: "0.5in" },
      displayHeaderFooter: false,
    });

    // Close the policy tab now that we have the PDF — avoids leaking tabs in
    // long-running Browserless sessions.
    await policyPage.close();

    const data = Buffer.from(pdfBytes);

    return [
      {
        type:     "DECLARATIONS",
        filename: `lemonade-policy-${policyId}.pdf`,
        mimeType: "application/pdf",
        data,
      },
    ];
  }

  // ─── Helpers ──────────────────────────────────────────────────────────────

  private static extractEmail(credentials: Record<string, string>): string {
    if (!credentials.email) {
      throw new Error("LemonadeCarrier: missing credential 'email'");
    }
    return credentials.email;
  }
}
